/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Follows: typeof import('./../components/follows/follows.vue')['default']
    List: typeof import('./../components/list/list.vue')['default']
    Refresh: typeof import('./../components/refresh/refresh.vue')['default']
    Rooms: typeof import('./../components/rooms/rooms.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../components/select/select.vue')['default']
    Slider: typeof import('./../components/slider/slider.vue')['default']
    Stepper: typeof import('./../components/stepper/stepper.vue')['default']
    Swipe: typeof import('./../components/swipe/swipe.vue')['default']
    SwipeItem: typeof import('./../components/swipe/swipeItem.vue')['default']
    Switch: typeof import('./../components/switch/switch.vue')['default']
    Tab: typeof import('./../components/tabs/tab.vue')['default']
    Tabs: typeof import('./../components/tabs/tabs.vue')['default']
  }
}
